#pragma once

#include <string>
#include <vector>

namespace GEO {
    class Mesh;
}

namespace georo {

    class Mesh;
    GEO::Mesh       &impl(Mesh &);
    const GEO::Mesh &impl(const Mesh &);

    // Thin marshalling wrapper around GEO::Mesh.
    //
    // GEO::Mesh cannot be bound directly by rosetta: its whole data API lives
    // in public member objects (mesh.vertices, mesh.facets, ...) that hold a
    // Mesh& back-reference (non copy-assignable) and expose raw double* /
    // index_t* accessors and GEO::vector containers — none of which a
    // scripting backend can marshal. This wrapper exposes the same geometry
    // as flat std::vector arrays and hides GEO::Mesh behind a pImpl so the
    // reflection generator never has to parse geogram headers.
    //
    // Vertices are flat [x0,y0,z0, x1,y1,z1, ...] arrays; triangles are flat
    // arrays of 3 vertex indices per triangle. Polygonal facets are
    // fan-triangulated on output by triangles() / tex_coords().
    class Mesh {
    public:
        Mesh();
        ~Mesh();

        // Load from any format supported by geogram
        // (.obj, .off, .ply, .stl, .mesh/.meshb, .geogram, ...).
        bool load(const std::string &filename);
        // Save to any format supported by geogram (chosen from the extension).
        bool save(const std::string &filename) const;
        // Remove all mesh elements.
        void clear();
        // Replace this mesh by a deep copy of another one.
        void assign(const Mesh &other);

        // Set the mesh to a point cloud. coordinates is a flat
        // [x0,y0,z0, x1,y1,z1, ...] array.
        void set_points(const std::vector<double> &coordinates);
        // Set the mesh to a triangulated surface. triangles is a flat array
        // of 3 vertex indices per triangle; facets are connected into a
        // combinatorial surface.
        void set_surface(const std::vector<double> &coordinates, const std::vector<int> &triangles);

        // Vertex coordinates as a flat [x0,y0,z0, ...] array.
        std::vector<double> vertices() const;
        // Triangle vertex indices, 3 per triangle. Polygonal facets are
        // fan-triangulated.
        std::vector<int> triangles() const;
        // Texture coordinates generated by make_atlas(), as a flat [u,v]
        // array with one entry per triangle corner, aligned with the output
        // of triangles() (i.e. 6 values per triangle). Empty if the mesh has
        // no "tex_coord" facet-corner attribute.
        std::vector<double> tex_coords() const;

        int nb_vertices() const;
        int nb_facets() const;

    private:
        friend GEO::Mesh       &impl(Mesh &);
        friend const GEO::Mesh &impl(const Mesh &);
        GEO::Mesh              *impl_;
    };

} // namespace georo
