#pragma once

#include "geogram_mesh.h"
#include <string>
#include <vector>

// Extension methods for GEO::Mesh (manifest class "extensions"): free
// functions whose first parameter is the mesh, exposed by rosetta as
// instance methods (mesh.load(...), mesh.vertices(), ...).
//
// They exist because this part of GEO::Mesh's API cannot cross a binding
// boundary directly: the geometry lives in public member objects
// (mesh.vertices, mesh.facets) with raw double* / index_t* accessors,
// mesh_load/mesh_save are overloaded (^^name is ill-formed for overloads),
// and the atlas UVs sit in a facet-corner attribute template. Everything
// here is stateless marshalling — no algorithmic code, no wrapper type.
//
// Vertices are flat [x0,y0,z0, x1,y1,z1, ...] arrays; triangles are flat
// arrays of 3 vertex indices per triangle. Polygonal facets are
// fan-triangulated on output by triangles() / tex_coords().
namespace georo {

    // Load from any format supported by geogram
    // (.obj, .off, .ply, .stl, .mesh/.meshb, .geogram, ...).
    bool load(GEO::Mesh &M, const std::string &filename);
    // Save to any format supported by geogram (chosen from the extension).
    bool save(const GEO::Mesh &M, const std::string &filename);

    // Set the mesh to a point cloud. coordinates is a flat
    // [x0,y0,z0, x1,y1,z1, ...] array.
    void set_points(GEO::Mesh &M, const std::vector<double> &coordinates);
    // Set the mesh to a triangulated surface. triangles is a flat array of
    // 3 vertex indices per triangle; facets are connected into a
    // combinatorial surface.
    void set_surface(GEO::Mesh &M, const std::vector<double> &coordinates,
                     const std::vector<int> &triangles);

    // Vertex coordinates as a flat [x0,y0,z0, ...] array.
    std::vector<double> vertices(const GEO::Mesh &M);
    // Triangle vertex indices, 3 per triangle (polygonal facets are
    // fan-triangulated).
    std::vector<int> triangles(const GEO::Mesh &M);
    // Texture coordinates generated by GEO::mesh_make_atlas, as a flat
    // [u,v] array with one entry per triangle corner, aligned with the
    // output of triangles(). Empty if the mesh has no "tex_coord"
    // facet-corner attribute.
    std::vector<double> tex_coords(const GEO::Mesh &M);

    int nb_vertices(const GEO::Mesh &M);
    int nb_facets(const GEO::Mesh &M);

} // namespace georo
