#pragma once

#include <geogram/mesh/mesh.h>
#include <vector>

// Extension methods for GEO::Mesh (manifest class "extensions"): free
// functions whose first parameter is the mesh, exposed by rosetta as
// instance methods (mesh.triangles(), mesh.tex_coords()).
//
// Down from seven functions to the two that encode POLICY no binding
// feature can absorb: fan-triangulation of polygonal facets on output.
// Everything else migrated to geogram's own API, bound directly:
//   set_points(c)      -> mesh.vertices.assign_points(c, 3, false)
//   set_surface(c, t)  -> mesh.facets.assign_triangle_mesh(3, c, t, false)
//                         (+ mesh_repair(M, DEFAULT, 0) when adjacency is
//                         needed — facets.connect() is an overload set and
//                         does not bind)
//   vertices()         -> mesh.vertices.point_coordinates()
//                         (call mesh.vertices.set_dimension(3) first when the
//                         mesh may be higher-dimensional, e.g. after
//                         remesh_smooth)
//   nb_vertices()      -> mesh.vertices.nb()
//   nb_facets()        -> mesh.facets.nb()
// GEO::vector<T> crosses the boundary via rosetta's sequence trait (manifest
// "sequences"), and mesh.vertices / mesh.facets are member-object properties
// (manifest "final" suppresses their trampolines so node reaches them too).
//
// Triangles are flat arrays of 3 vertex indices per triangle; tex coords are
// flat [u,v] per triangle corner, aligned with triangles().
namespace georo {

    // Triangle vertex indices, 3 per triangle. A triangulated mesh is a bulk
    // copy of mesh.facet_corners.vertex_indices(); polygonal facets are
    // fan-triangulated.
    std::vector<int> triangles(const GEO::Mesh &M);

    // Texture coordinates generated by GEO::mesh_make_atlas, as a flat
    // [u,v] array with one entry per triangle corner, aligned with the
    // output of triangles() (same fan order). Empty if the mesh has no
    // "tex_coord" facet-corner attribute.
    std::vector<double> tex_coords(const GEO::Mesh &M);

} // namespace georo
